include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_key_in_widget_constructors: true
