name: calculateprice_app
description: "Calculate the best price app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  macos: 
    image_path: "assets/icons/app_icon.png"
  web:
    image_path: "assets/icons/app_icon.png"
  image_path: "assets/icon/app_icon.png" 
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" 
  adaptive_icon_background: "assets/icon/app_icon_background.png"
